# Generated by Django 6.0.3 on 2026-04-06 11:36

import apps.products.utils.path_utility
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=apps.products.utils.path_utility.product_image_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='shtrix_code',
            field=models.ImageField(upload_to=apps.products.utils.path_utility.product_barcode_path),
        ),
    ]
