# Generated by Django 5.2.13 on 2026-04-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_category_options_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbatch',
            name='barcode',
            field=models.CharField(db_index=True, max_length=13, unique=True),
        ),
    ]
