# Generated by Django 5.2.13 on 2026-04-23 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_productbatch_barcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.TextField()),
                ('location_uz', models.TextField(null=True)),
                ('location_uz_cyrl', models.TextField(null=True)),
                ('description', models.TextField()),
                ('description_uz', models.TextField(null=True)),
                ('description_uz_cyrl', models.TextField(null=True)),
            ],
            options={
                'db_table': 'product_location',
            },
        ),
        migrations.CreateModel(
            name='ProductUnitMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('measurement', models.CharField(max_length=50)),
                ('measurement_uz', models.CharField(max_length=50, null=True)),
                ('measurement_uz_cyrl', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'product_unit_measurement',
            },
        ),
        migrations.AddField(
            model_name='productbatch',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.productlocation'),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='unit_measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.productunitmeasurement'),
        ),
    ]
