# Generated by Django 5.2.13 on 2026-04-23 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productlocation_productunitmeasurement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbatch',
            name='unit_measurement',
        ),
        migrations.AddField(
            model_name='product',
            name='unit_measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.productunitmeasurement'),
        ),
    ]
