# Generated by Django 5.2.13 on 2026-05-25 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productbatch',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.category'),
        ),
    ]
