# Generated by Django 5.2.13 on 2026-05-25 10:05

import apps.products.utils.path_utility
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_brand_options_remove_product_shtrix_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shtrix_code',
            field=models.ImageField(blank=True, null=True, upload_to=apps.products.utils.path_utility.product_barcode_path),
        ),
    ]
