# Generated by Django 5.2.13 on 2026-05-25 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_shtrix_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
    ]
