# Generated by Django 5.2.13 on 2026-05-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='name_uz',
            field=models.CharField(db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_uz_cyrl',
            field=models.CharField(db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
