# Generated by Django 5.2.13 on 2026-06-12 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_brand_name_uz_brand_name_uz_cyrl'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatch',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
