# Generated by Django 5.2.13 on 2026-06-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_productbatch_wholesale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatch',
            name='min_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
