# Generated by Django 5.2.13 on 2026-06-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_move_min_stock_to_product'),
        ('store', '0004_store_address_uz_store_address_uz_cyrl_store_name_uz_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productbatch',
            constraint=models.UniqueConstraint(fields=('store', 'product'), name='uniq_product_batch_store_product'),
        ),
    ]
