# Generated by Django 5.2.13 on 2026-08-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_backfill_missing_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_pair',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
