# Generated by Django 5.2.13 on 2026-08-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_product_is_pair_alter_productbatch_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunitmeasurement',
            name='quantity_type',
            field=models.CharField(choices=[('WHOLE', 'Dona'), ('QUARTER', 'Juft')], db_index=True, default='WHOLE', max_length=20),
        ),
    ]
