# Generated by Django 5.2.13 on 2026-08-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_sync_unit_quantity_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatch',
            name='min_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
