# Generated by Django 5.2.13 on 2026-08-27 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_productbatch_min_stock_alter_product_min_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFieldHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_name', models.CharField(db_index=True, max_length=64)),
                ('field_label', models.CharField(max_length=128)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('user_display', models.CharField(blank=True, default='', max_length=160)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_histories', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product_field_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'created_at'], name='product_fie_product_304b59_idx')],
            },
        ),
    ]
