# Generated by Django 5.2.13 on 2026-09-08 11:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_productfieldhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brands/logos/'),
        ),
        migrations.CreateModel(
            name='BarcodeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('width_mm', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('15.00')), django.core.validators.MaxValueValidator(Decimal('150.00'))])),
                ('height_mm', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('10.00')), django.core.validators.MaxValueValidator(Decimal('150.00'))])),
                ('barcode_format', models.CharField(choices=[('EAN13', 'EAN-13')], default='EAN13', max_length=20)),
                ('layout', models.JSONField(default=dict)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_barcode_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'barcode_template',
                'ordering': ['-is_default', 'name'],
                'indexes': [models.Index(fields=['is_default', 'is_active'], name='barcode_tem_is_defa_2bb851_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default', True)), fields=('is_default',), name='uniq_active_default_barcode_template')],
            },
        ),
    ]
