# Generated by Django 5.2.13 on 2026-09-09 07:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_seed_default_barcode_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='barcodetemplate',
            name='uniq_active_default_barcode_template',
        ),
        migrations.RemoveIndex(
            model_name='barcodetemplate',
            name='barcode_tem_is_defa_2bb851_idx',
        ),
        migrations.RemoveField(
            model_name='barcodetemplate',
            name='is_active',
        ),
        migrations.AddConstraint(
            model_name='barcodetemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='uniq_default_barcode_template'),
        ),
    ]
