# Generated by Django 5.2.13 on 2026-06-29 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0007_lowstockitem'),
        ('products', '0021_move_min_stock_to_product'),
        ('store', '0004_store_address_uz_store_address_uz_cyrl_store_name_uz_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WriteOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('damaged', 'Buzilgan / yaroqsiz'), ('expired', "Muddati o'tgan"), ('lost', "Yo'qolgan / o'g'irlangan"), ('inventory', 'Inventarizatsiya kamomadi'), ('catalog', 'Katalogdan chiqarish'), ('other', 'Boshqa')], db_index=True, default='other', max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='write_offs', to=settings.AUTH_USER_MODEL)),
                ('inventory_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='write_offs', to='inventory.inventorysession')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='write_offs', to='store.store')),
            ],
            options={
                'db_table': 'write_off',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WriteOffItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('write_off', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='writeoff.writeoff')),
            ],
            options={
                'db_table': 'write_off_item',
            },
        ),
        migrations.AddIndex(
            model_name='writeoff',
            index=models.Index(fields=['store', 'reason'], name='write_off_store_i_ed4a74_idx'),
        ),
        migrations.AddIndex(
            model_name='writeoff',
            index=models.Index(fields=['-created_at'], name='write_off_created_e7b316_idx'),
        ),
        migrations.AddIndex(
            model_name='writeoffitem',
            index=models.Index(fields=['write_off'], name='write_off_i_write_o_fd1b38_idx'),
        ),
        migrations.AddIndex(
            model_name='writeoffitem',
            index=models.Index(fields=['product'], name='write_off_i_product_c5bc08_idx'),
        ),
    ]
