# Generated by Django 6.0.3 on 2026-04-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_saleitem_total_price_alter_saleitem_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
