# Generated by Django 5.2.13 on 2026-04-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_sale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
