# Generated by Django 5.2.13 on 2026-04-18 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_saleitem_purchase_price'),
        ('users', '0004_customer_created_at_customer_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='users.customer'),
        ),
    ]
