# Generated by Django 5.2.13 on 2026-04-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_saleitem_returned_quantity_salereturn_salereturnitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partial'), ('debt', 'Debt'), ('r', 'Returned')], db_index=True, max_length=10),
        ),
    ]
