# Generated by Django 5.2.13 on 2026-07-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_backfill_sale_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankcard',
            name='scope',
            field=models.CharField(choices=[('sale', 'Faqat sotuv'), ('purchase', 'Faqat kirim'), ('both', 'Sotuv va kirim')], db_index=True, default='both', max_length=10),
        ),
    ]
