# Generated by Django 5.2.13 on 2026-07-18 05:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_bankcard_scope'),
        ('store', '0004_store_address_uz_store_address_uz_cyrl_store_name_uz_and_more'),
        ('users', '0007_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['-created_at'], name='sales_sale_created_66311a_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['store', '-created_at'], name='sales_sale_store_i_8c6d9d_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['seller', '-created_at'], name='sales_sale_seller__7d4b28_idx'),
        ),
    ]
