# Generated by Django 5.2.13 on 2026-07-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_sale_sales_sale_created_66311a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
