# Generated by Django 5.2.13 on 2026-07-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_sale_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_group',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
