# Generated by Django 5.2.13 on 2026-07-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_backfill_payment_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='salereturn',
            name='payment_group',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
