# Generated by Django 5.2.13 on 2026-07-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_backfill_salereturn_payment_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_debt_payment',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
