# Generated by Django 6.0.3 on 2026-04-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeuser',
            name='role',
            field=models.CharField(choices=[('o', 'Owner'), ('m', 'Manager'), ('s', 'Seller')], max_length=20),
        ),
    ]
