# Generated by Django 6.0.3 on 2026-04-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_storeuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeuser',
            name='role',
            field=models.CharField(choices=[('m', 'Manager'), ('s', 'Seller')], max_length=20),
        ),
    ]
