# Generated by Django 6.0.3 on 2026-04-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_storeuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='address_uz_cyrl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_uz_cyrl',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
