# Generated by Django 5.2.13 on 2026-10-05 11:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0004_store_address_uz_store_address_uz_cyrl_store_name_uz_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('stock_entry_import', 'Kirim importi'), ('product_import', 'Mahsulotlar importi'), ('excel_export', 'Excel eksport')], db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Bajarilmoqda'), ('completed', 'Muvaffaqiyatli yakunlandi'), ('failed', 'Xatolik bilan tugadi'), ('cancelled', 'Bekor qilindi')], db_index=True, default='pending', max_length=32)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('input_file', models.FileField(blank=True, null=True, upload_to='async_jobs/inputs/%Y/%m/')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='async_jobs/outputs/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='async_jobs', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='async_jobs', to='store.store')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='common_asyn_status_4c2bcc_idx'), models.Index(fields=['store', 'job_type'], name='common_asyn_store_i_05f37c_idx')],
            },
        ),
    ]
