# Generated by Django 5.2.13 on 2026-07-15 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_seed_default_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_display', models.CharField(blank=True, default='', max_length=160)),
                ('module', models.CharField(db_index=True, max_length=32)),
                ('action', models.CharField(choices=[('create', "Qo'shish"), ('edit', 'Tahrirlash'), ('delete', "O'chirish"), ('archive', 'Arxivlash'), ('login', 'Kirish'), ('logout', 'Chiqish')], db_index=True, max_length=16)),
                ('method', models.CharField(blank=True, default='', max_length=8)),
                ('path', models.CharField(blank=True, default='', max_length=255)),
                ('object_id', models.CharField(blank=True, default='', max_length=32)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['module', 'action'], name='audit_log_module_2b88a0_idx')],
            },
        ),
    ]
