# Generated by Django 5.2.13 on 2026-04-22 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0009_alter_productbatch_barcode'),
        ('store', '0004_store_address_uz_store_address_uz_cyrl_store_name_uz_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('snapshot_taken', models.BooleanField(default=False)),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
            options={
                'db_table': 'inventory_session',
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('type', models.CharField(choices=[('sale', 'Sale'), ('transfer_out', 'Transfer Out')], max_length=20)),
                ('ref_id', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventorysession')),
            ],
            options={
                'db_table': 'inventory_movement',
            },
        ),
        migrations.CreateModel(
            name='InventoryCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counted_quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='inventory.inventorysession')),
            ],
            options={
                'db_table': 'inventory_count',
            },
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('difference', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventorysession')),
            ],
            options={
                'db_table': 'inventory_adjustment',
            },
        ),
        migrations.CreateModel(
            name='InventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='inventory.inventorysession')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
            options={
                'db_table': 'inventory_snapshot',
            },
        ),
        migrations.AddIndex(
            model_name='inventorysession',
            index=models.Index(fields=['store', 'status'], name='inventory_s_store_i_5d245d_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['session', 'product'], name='inventory_m_session_5730cd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorycount',
            unique_together={('session', 'product')},
        ),
        migrations.AddIndex(
            model_name='inventoryadjustment',
            index=models.Index(fields=['session'], name='inventory_a_session_f7be3d_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorysnapshot',
            index=models.Index(fields=['session', 'product'], name='inventory_s_session_43a0b7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorysnapshot',
            unique_together={('session', 'product')},
        ),
    ]
