# Generated by Django 5.2.13 on 2026-04-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycount',
            name='is_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventorycount',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('equal', 'Equal'), ('less', 'Less'), ('more', 'More')], default='pending', max_length=10),
        ),
        migrations.AlterModelTable(
            name='inventorycount',
            table=None,
        ),
    ]
