# Generated by Django 5.2.13 on 2026-04-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorycount_is_check_inventorycount_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycount',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('e', 'Equal'), ('l', 'Less'), ('m', 'More')], default='p', max_length=10),
        ),
    ]
