# Generated by Django 5.2.13 on 2026-04-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventorycount_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='type',
            field=models.CharField(choices=[('sale', 'Sale'), ('transfer_out', 'Transfer Out'), ('return', 'Return')], max_length=20),
        ),
    ]
