# Generated by Django 5.2.13 on 2026-04-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventorymovement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='type',
            field=models.CharField(choices=[('s', 'Sale'), ('to', 'Transfer Out'), ('r', 'Return'), ('ti', 'Transfer In'), ('e', 'Entry')], max_length=20),
        ),
    ]
