# Generated by Django 5.2.13 on 2026-05-14 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventorymovement_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorysession',
            options={'ordering': ['-created_at']},
        ),
    ]
