# Generated by Django 5.2.13 on 2026-06-17 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventorysession_options'),
        ('products', '0020_productbatch_min_stock'),
        ('store', '0004_store_address_uz_store_address_uz_cyrl_store_name_uz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LowStockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_quantity', models.IntegerField()),
                ('min_stock', models.PositiveIntegerField()),
                ('action_type', models.CharField(choices=[('purchase', 'Purchase (supplier)'), ('transfer', 'Transfer (from base)')], max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=10)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_stock_items', to='products.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_stock_items', to='store.store')),
            ],
            options={
                'db_table': 'low_stock_item',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'action_type'], name='low_stock_i_status_b4bc36_idx'), models.Index(fields=['store', 'status'], name='low_stock_i_store_i_329cb9_idx'), models.Index(fields=['product', 'status'], name='low_stock_i_product_de618d_idx'), models.Index(fields=['status', '-created_at'], name='low_stock_i_status_573607_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('store', 'product'), name='uniq_open_low_stock_per_store_product')],
            },
        ),
    ]
