# Generated by Django 5.2.13 on 2026-07-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_lowstockitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycount',
            name='counted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
