# Generated by Django 5.2.13 on 2026-08-09 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_inventorycount_counted_at'),
        ('products', '0024_product_is_pair_alter_productbatch_quantity'),
        ('store', '0004_store_address_uz_store_address_uz_cyrl_store_name_uz_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryadjustment',
            name='difference',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='inventorycount',
            name='counted_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='inventorysnapshot',
            name='expected_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='lowstockitem',
            name='current_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_quantity', models.IntegerField()),
                ('new_quantity', models.IntegerField()),
                ('difference', models.IntegerField()),
                ('reason', models.CharField(choices=[('recount', 'Qayta sanash'), ('data_error', "Xato kiritilgan ma'lumot"), ('damaged', 'Buzilgan / yaroqsiz'), ('found', 'Topilgan tovar'), ('other', 'Boshqa')], db_index=True, default='recount', max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_adjustments', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments', to='products.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments', to='store.store')),
            ],
            options={
                'db_table': 'stock_adjustment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', 'product'], name='stock_adjus_store_i_d08ac9_idx'), models.Index(fields=['-created_at'], name='stock_adjus_created_99b845_idx')],
            },
        ),
    ]
