# Generated by Django 5.2.13 on 2026-08-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_inventoryadjustment_difference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='difference',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='new_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='old_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
