# Generated by Django 5.2.13 on 2026-08-27 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_stockadjustment_difference_and_more'),
        ('products', '0026_sync_unit_quantity_types'),
        ('store', '0004_store_address_uz_store_address_uz_cyrl_store_name_uz_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_stock_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='status',
            field=models.CharField(choices=[('active', 'Faol'), ('cancelled', 'Bekor qilingan')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='type',
            field=models.CharField(choices=[('import', 'Import'), ('write_off', 'Hisobdan chiqarish'), ('recount', 'Qayta sanash')], db_index=True, default='import', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='difference',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='new_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='old_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='reason',
            field=models.CharField(choices=[('manual_import', "Qo'lda kirim / Import"), ('recount', 'Qayta sanash'), ('data_error', "Xato kiritilgan ma'lumot"), ('damaged', 'Buzilgan / yaroqsiz'), ('expired', "Muddati o'tgan"), ('lost', "Yo'qolgan / o'g'irlangan"), ('found', 'Topilgan tovar'), ('other', 'Boshqa')], db_index=True, default='manual_import', max_length=20),
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['type', 'status'], name='stock_adjus_type_02b389_idx'),
        ),
    ]
