# Generated by Django 5.2.13 on 2026-08-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_stockadjustment_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowstockitem',
            name='min_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
