# Generated by Django 5.2.13 on 2026-09-11 06:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0017_alter_stockentryitem_quantity_and_more'),
        ('inventory', '0012_alter_lowstockitem_min_stock'),
        ('products', '0031_remove_barcodetemplate_uniq_active_default_barcode_template_and_more'),
        ('sales', '0024_alter_saleitem_quantity_and_more'),
        ('store', '0004_store_address_uz_store_address_uz_cyrl_store_name_uz_and_more'),
        ('transfer', '0009_alter_stocktransferitem_quantity'),
        ('writeoff', '0002_alter_writeoffitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot_type', models.CharField(choices=[('purchase', 'Purchase'), ('transfer_in', 'Transfer In'), ('inventory_excess', 'Inventory Excess'), ('opening_balance', 'Opening Balance')], db_index=True, default='purchase', max_length=30)),
                ('initial_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining_quantity', models.DecimalField(db_index=True, decimal_places=2, max_digits=12)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_lots', to='products.product')),
                ('source_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_lots', to='inventory.stocklot')),
                ('stock_entry_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_lots', to='contract.stockentryitem')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_lots', to='store.store')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_lots', to='contract.supplier')),
            ],
            options={
                'db_table': 'stock_lot',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StockAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('sale', 'Sale'), ('sale_return', 'Sale Return'), ('write_off', 'Write Off'), ('transfer_out', 'Transfer Out'), ('transfer_in', 'Transfer In'), ('inventory_shortage', 'Inventory Shortage'), ('inventory_excess', 'Inventory Excess'), ('supplier_return', 'Supplier Return')], db_index=True, max_length=30)),
                ('direction', models.CharField(choices=[('in', 'In'), ('out', 'Out')], db_index=True, max_length=5)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sale_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_allocations', to='sales.saleitem')),
                ('sale_return_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_allocations', to='sales.salereturnitem')),
                ('supplier_return_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_allocations', to='contract.stockentryreturnitem')),
                ('transfer_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_allocations', to='transfer.stocktransferitem')),
                ('write_off_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_allocations', to='writeoff.writeoffitem')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='inventory.stocklot')),
            ],
            options={
                'db_table': 'stock_allocation',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='stocklot',
            index=models.Index(fields=['store', 'product', 'remaining_quantity', 'created_at'], name='stock_lot_store_prod_rem_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklot',
            index=models.Index(fields=['supplier', 'product'], name='stock_lot_supplier_prod_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklot',
            index=models.Index(condition=models.Q(('remaining_quantity__gt', 0)), fields=['store', 'product', 'created_at'], name='stock_lot_fifo_partial_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklot',
            index=models.Index(fields=['created_at'], name='stock_lot_created_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocklot',
            constraint=models.CheckConstraint(condition=models.Q(('initial_quantity__gt', 0)), name='stock_lot_initial_qty_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='stocklot',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_quantity__gte', 0)), name='stock_lot_remaining_qty_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='stocklot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lot_type', 'transfer_in'), _negated=True), ('source_lot__isnull', False), _connector='OR'), name='stock_lot_transfer_in_has_source'),
        ),
        migrations.AddConstraint(
            model_name='stocklot',
            constraint=models.CheckConstraint(condition=models.Q(('source_lot__isnull', True), models.Q(('source_lot', models.F('id')), _negated=True), _connector='OR'), name='stock_lot_prevent_self_reference'),
        ),
        migrations.AddIndex(
            model_name='stockallocation',
            index=models.Index(fields=['lot', 'created_at'], name='stock_alloc_lot_created_idx'),
        ),
        migrations.AddIndex(
            model_name='stockallocation',
            index=models.Index(fields=['movement_type', 'created_at'], name='stock_alloc_mov_type_idx'),
        ),
        migrations.AddIndex(
            model_name='stockallocation',
            index=models.Index(fields=['sale_item'], name='stock_alloc_sale_item_idx'),
        ),
        migrations.AddIndex(
            model_name='stockallocation',
            index=models.Index(fields=['sale_return_item'], name='stock_alloc_return_item_idx'),
        ),
        migrations.AddIndex(
            model_name='stockallocation',
            index=models.Index(fields=['write_off_item'], name='stock_alloc_woff_item_idx'),
        ),
        migrations.AddIndex(
            model_name='stockallocation',
            index=models.Index(fields=['transfer_item'], name='stock_alloc_trans_item_idx'),
        ),
        migrations.AddIndex(
            model_name='stockallocation',
            index=models.Index(fields=['supplier_return_item'], name='stock_alloc_sup_ret_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockallocation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='stock_allocation_qty_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='stockallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type__in', ['sale', 'write_off', 'transfer_out', 'inventory_shortage', 'supplier_return']), ('direction', 'out')), models.Q(('movement_type__in', ['sale_return', 'transfer_in', 'inventory_excess']), ('direction', 'in')), _connector='OR'), name='stock_allocation_movement_direction_match'),
        ),
        migrations.AddConstraint(
            model_name='stockallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type', 'sale'), ('sale_item__isnull', False), ('sale_return_item__isnull', True), ('write_off_item__isnull', True), ('transfer_item__isnull', True), ('supplier_return_item__isnull', True)), models.Q(('movement_type', 'sale_return'), ('sale_item__isnull', True), ('sale_return_item__isnull', False), ('write_off_item__isnull', True), ('transfer_item__isnull', True), ('supplier_return_item__isnull', True)), models.Q(('movement_type', 'write_off'), ('sale_item__isnull', True), ('sale_return_item__isnull', True), ('write_off_item__isnull', False), ('transfer_item__isnull', True), ('supplier_return_item__isnull', True)), models.Q(('movement_type__in', ['transfer_out', 'transfer_in']), ('sale_item__isnull', True), ('sale_return_item__isnull', True), ('write_off_item__isnull', True), ('transfer_item__isnull', False), ('supplier_return_item__isnull', True)), models.Q(('movement_type', 'supplier_return'), ('sale_item__isnull', True), ('sale_return_item__isnull', True), ('write_off_item__isnull', True), ('transfer_item__isnull', True), ('supplier_return_item__isnull', False)), models.Q(('movement_type__in', ['inventory_shortage', 'inventory_excess']), ('sale_item__isnull', True), ('sale_return_item__isnull', True), ('write_off_item__isnull', True), ('transfer_item__isnull', True), ('supplier_return_item__isnull', True)), _connector='OR'), name='stock_allocation_source_exclusivity'),
        ),
    ]
