# Generated by Django 5.2.13 on 2026-09-11 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0017_alter_stockentryitem_quantity_and_more'),
        ('inventory', '0013_stocklot_stockallocation_and_more'),
        ('sales', '0024_alter_saleitem_quantity_and_more'),
        ('transfer', '0009_alter_stocktransferitem_quantity'),
        ('writeoff', '0002_alter_writeoffitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockallocation',
            name='inventory_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_allocations', to='inventory.inventorysession'),
        ),
        migrations.AddField(
            model_name='stockallocation',
            name='reversal_of',
            field=models.ForeignKey(blank=True, help_text='Ushbu allocation bekor qilayotgan asl OUT allocation.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='inventory.stockallocation'),
        ),
        migrations.AddIndex(
            model_name='stockallocation',
            index=models.Index(fields=['movement_type', 'created_at', 'lot'], name='stock_alloc_rep_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockallocation',
            constraint=models.CheckConstraint(condition=models.Q(('movement_type', 'sale_return'), ('reversal_of__isnull', True), _connector='OR'), name='stock_alloc_reversal_only_sale_return'),
        ),
        migrations.AddConstraint(
            model_name='stockallocation',
            constraint=models.CheckConstraint(condition=models.Q(('reversal_of__isnull', True), models.Q(('reversal_of', models.F('id')), _negated=True), _connector='OR'), name='stock_alloc_prevent_self_reversal'),
        ),
        migrations.AddConstraint(
            model_name='stockallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type__in', ['inventory_shortage', 'inventory_excess']), ('inventory_session__isnull', False)), models.Q(models.Q(('movement_type__in', ['inventory_shortage', 'inventory_excess']), _negated=True), ('inventory_session__isnull', True)), _connector='OR'), name='stock_alloc_inventory_session_match'),
        ),
    ]
