"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from .config import *
from django.utils.translation import gettext_lazy as _

from core.settings.config import DEFAULT_APPS, THIRD_PARTY_APPS, LOCAL_APPS


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')


# ========================   Application definition  ==========================================

INSTALLED_APPS = [
    *DAPHNE_APP,
    *DEFAULT_APPS,
    *THIRD_PARTY_APPS,
    *LOCAL_APPS,
]

# Application definition

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "django.middleware.locale.LocaleMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    "core.middleware.rbac.RBACMiddleware",
    "core.middleware.store_context.StoreContextMiddleware",
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.request_logger.RequestLoggerMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'assets/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# ========================  Language / Internationalization  ==========================================
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGES = [
    ("uz", _("Uzbek (Latin)")),
    ("uz-cyrl", _("Uzbek (Cyrillic)")),
]

PARLER_LANGUAGES = {
    None: (
        {"code": "uz"},
        {"code": "uz-cyrl"},
    ),
    "default": {
        "fallbacks": ["uz"],
        "hide_untranslated": False,
    }
}


LOCALE_PATHS = [
    BASE_DIR / "locale",
]

LANGUAGE_CODE = 'uz'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# ModelTranslation uchun
MODELTRANSLATION_DEFAULT_LANGUAGE = 'uz'

# ========================  Static files (CSS, JavaScript, Images)  ==========================================
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
# STATICFILES_DIRS = [
#     BASE_DIR / "assets/static"
# ]
STATIC_ROOT = BASE_DIR / 'assets/staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'assets/media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.User'


# ========================  Email settings  ==========================================
# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_PORT = config('EMAIL_PORT', cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')

# Password reset timeout (1 hour)
# PASSWORD_RESET_TIMEOUT = config('PASSWORD_RESET_TIMEOUT', cast=int, default=3600)

# ========================  LOgging ==========================================
# Logging (productionda file yoki cloud loggingga o'tkazish)
import logging
logging.basicConfig(level=logging.INFO)

# ==============================   CHANNEL Redis  ======================================

ASGI_APPLICATION = "core.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}