# Generated by Django 6.0.3 on 2026-04-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='address_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='address_uz_cyrl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='description_uz_cyrl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='name_uz_cyrl',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
