# Generated by Django 6.0.3 on 2026-04-08 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_supplier_address_uz_supplier_address_uz_cyrl_and_more'),
        ('products', '0007_alter_productbatch_product'),
        ('store', '0004_store_address_uz_store_address_uz_cyrl_store_name_uz_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='store.store')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='contract.supplier')),
            ],
            options={
                'db_table': 'stock_entry',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockEntryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contract.stockentry')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'db_table': 'stock_entry_item',
            },
        ),
    ]
