# Generated by Django 5.2.13 on 2026-05-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_stockentry_paid_amount_stockentry_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('op', 'Online Payment')], default='cash', max_length=7),
        ),
    ]
