# Generated by Django 5.2.13 on 2026-05-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_stockentry_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='inn',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
