# Generated by Django 5.2.13 on 2026-07-15 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_stockentry_card_amount_stockentry_cash_amount_and_more'),
        ('sales', '0013_bankcard_scope'),
        ('store', '0004_store_address_uz_store_address_uz_cyrl_store_name_uz_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='bank_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='sales.bankcard'),
        ),
        migrations.CreateModel(
            name='PurchaseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('items', models.JSONField(blank=True, default=list)),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('card_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('in_progress', 'Jarayonda'), ('received', 'Qabul qilingan (tasdiqlanmagan)'), ('completed', 'Tasdiqlangan'), ('cancelled', 'Bekor qilingan')], db_index=True, default='in_progress', max_length=12)),
                ('current_step', models.PositiveSmallIntegerField(default=1)),
                ('bank_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_sessions', to='sales.bankcard')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_sessions', to=settings.AUTH_USER_MODEL)),
                ('entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session', to='contract.stockentry')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_sessions', to='store.store')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_sessions', to='contract.supplier')),
            ],
            options={
                'db_table': 'purchase_session',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['created_by', 'status'], name='purchase_se_created_922dbf_idx')],
            },
        ),
    ]
