# Generated by Django 5.2.13 on 2026-07-15 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0008_stockentry_bank_card_purchasesession'),
        ('sales', '0013_bankcard_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliertransaction',
            name='bank_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_transactions', to='sales.bankcard'),
        ),
        migrations.AddField(
            model_name='suppliertransaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Naqd'), ('card', 'Karta')], default='', max_length=5),
        ),
    ]
