# Generated by Django 5.2.13 on 2026-07-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0009_suppliertransaction_bank_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasesession',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
