# Generated by Django 5.2.13 on 2026-07-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0010_purchasesession_note_stockentry_note'),
        ('sales', '0013_bankcard_scope'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='suppliertransaction',
            index=models.Index(fields=['type', 'created_at'], name='supplier_tr_type_31284d_idx'),
        ),
    ]
