# Generated by Django 5.2.13 on 2026-07-22 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0011_suppliertransaction_supplier_tr_type_31284d_idx'),
        ('sales', '0015_sale_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasesession',
            name='payments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='StockEntryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('type', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta')], max_length=5)),
                ('bank_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_entry_payments', to='sales.bankcard')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contract.stockentry')),
            ],
            options={
                'db_table': 'stock_entry_payment',
                'indexes': [models.Index(fields=['type', 'created_at'], name='stock_entry_type_5a76f0_idx')],
            },
        ),
    ]
