# Generated by Django 5.2.13 on 2026-07-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0013_backfill_stock_entry_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliertransaction',
            name='payment_group',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
