# Generated by Django 5.2.13 on 2026-07-27 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0015_backfill_supplier_payment_groups'),
        ('products', '0023_backfill_missing_sku'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliertransaction',
            name='type',
            field=models.CharField(choices=[('in', 'Inventory Intake (Debt Increase)'), ('pay', 'Payment to Supplier (Debt Decrease)'), ('ret', 'Return to Supplier (Debt Decrease)')], max_length=5),
        ),
        migrations.CreateModel(
            name='StockEntryReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('debt_cancelled', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('note', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='contract.stockentry')),
            ],
            options={
                'db_table': 'stock_entry_return',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockEntryReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('entry_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='contract.stockentryitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('stock_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contract.stockentryreturn')),
            ],
            options={
                'db_table': 'stock_entry_return_item',
            },
        ),
        migrations.AddIndex(
            model_name='stockentryreturn',
            index=models.Index(fields=['created_at'], name='stock_entry_created_ac6e72_idx'),
        ),
    ]
