# Generated by Django 5.2.13 on 2026-08-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0016_alter_suppliertransaction_type_stockentryreturn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentryitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockentryreturnitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
