# Generated by Django 6.0.3 on 2026-04-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransfer',
            name='barcode',
            field=models.CharField(max_length=12),
        ),
    ]
