# Generated by Django 6.0.3 on 2026-04-10 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_category_options_alter_product_options'),
        ('transfer', '0003_alter_stocktransfer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransfer',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stocktransfer',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='stocktransfer',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='stocktransfer',
            name='selling_price',
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('a', 'Approved'), ('r', 'Rejected')], default='p', max_length=1),
        ),
        migrations.CreateModel(
            name='StockTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('stock_transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transfer.stocktransfer')),
            ],
            options={
                'db_table': 'stock_transfer_item',
                'ordering': ['-created_at'],
            },
        ),
    ]
