# Generated by Django 5.2.13 on 2026-06-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0005_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('tc', 'Transfer Created'), ('ta', 'Transfer Approved'), ('tr', 'Transfer Rejected'), ('lp', 'Low Stock - Purchase Required'), ('lt', 'Low Stock - Transfer Required')], max_length=20),
        ),
    ]
