# Generated by Django 5.2.13 on 2026-08-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0008_alter_stocktransferitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransferitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
