# Generated by Django 6.0.3 on 2026-04-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdebt',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
