# Generated by Django 5.2.13 on 2026-06-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0003_alter_customerdebt_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdebt',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
