# Generated by Django 5.2.13 on 2026-07-28 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0004_customerdebt_due_date'),
        ('users', '0008_assign_role_to_roleless_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdebt',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debts', to='users.customer'),
        ),
    ]
